name: workflow-test

on:
  push:
    branches: 
      - feature/ci_* 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout FE-project repository
      uses: actions/checkout@v1

    - name: Install Fortran compiler & NetCDF  & OpenMPI & lapack & openssh
      run: |
        echo "Install Fortran compiler .."
        sudo apt-get install -y gfortran
        
        echo "Install NetCDF library .."
        sudo apt-get install -y libnetcdf-dev libnetcdff-dev

        echo "Install OpenMPI library .."
        sudo apt-get install -y openmpi-bin libopenmpi-dev

        echo "Install lapack .."
        sudo apt-get install -y libopenblas-dev liblapack-dev

        echo "Install openssh .."
        sudo apt-get install -y openssh-client

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_KEY }} 
        public-key: ${{ secrets.SSH_KEY_PUBLIC }} 
        name: id_rsa
        
    - name: Install SCALE library
      run: |
        sed -i -e "s#\\\\n#\n#g" ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H www.gfd-dennou.org >> ~/.ssh/known_hosts
        cd ${GITHUB_WORKSPACE}/.. 
        scp ykawai@www.gfd-dennou.org:FE-Project_GitActions/scalelib_ubuntu_latest.zip .
        unzip scalelib_ubuntu_latest.zip && mv scalelib_ubuntu_latest scale
  
    - name: Build FElib
      run: |
        echo "Build FE library .."
        export SCALE_FE_SYS=Linux64-gnu-ompi
        export SCALE=${GITHUB_WORKSPACE}/../scale
        make -C FElib/src

    - name: unit test for FElib
      run: | 
        echo "Perform unit tests .."

        export SCALE_FE_SYS=Linux64-gnu-ompi
        export SCALE=${GITHUB_WORKSPACE}/../scale

        cd FElib/test/FE
        make -C polynominal
        make -C mesh_linedom1d
        make -C mesh_rectdom2d_quadrilateral
        make -C field_linedom1d
        make -C field_rectdom2d_quadrilateral
        

      

      



